### ISSUE TITLE
Setup L2TP VPN for MikroTik

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/spynet#19]
* [x] start L2TP server

This checks the state of L2TP server.
```
[admin@MHS-MikroTik] /interface l2tp-server> server print 
               enabled: no
               max-mtu: 1450
               max-mru: 1450
                  mrru: disabled
        authentication: pap,chap,mschap1,mschap2
     keepalive-timeout: 30
          max-sessions: unlimited
       default-profile: default-encryption
             use-ipsec: no
          ipsec-secret: 
        caller-id-type: ip-address
  one-session-per-host: no
       allow-fast-path: no
```
This enables it.
```
/interface l2tp-server server
set enabled=yes use-ipsec=required ipsec-secret=strongpassis...
```
The final status.
```
[admin@MHS-MikroTik] /interface l2tp-server server> print 
               enabled: yes
               max-mtu: 1450
               max-mru: 1450
                  mrru: disabled
        authentication: pap,chap,mschap1,mschap2
     keepalive-timeout: 30
          max-sessions: unlimited
       default-profile: default-encryption
             use-ipsec: required
          ipsec-secret: strongpassis...
        caller-id-type: ip-address
  one-session-per-host: no
       allow-fast-path: no
```

* [ ] set firewall to enable connections to L2TP 

Using any L2TP client try to connect to malino.mhs.by and watch the response with `Wireshark`. If there is no response, them MikroTik firewall needs to be configured to allow L2TP UDP port 1701 to pass.
```
/ip firewall filter
add chain=input protocol=udp port=1701
```
https://wiki.mikrotik.com/wiki/Manual:Interface/L2TP#Basic_L2TP.2FIpSec_setup
