### ISSUE TITLE
vpn over ip

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/spynet#5]
https://www.tinc-vpn.org/

**Comment by Olgerd96** [comment]
могу найти лишний микротик... поставить его вместо зухеля, чтобы он и VPN в интернет поднимал и какой нибудь VPN over IPSec поднимал :)
есть даже RackMount (там 5 гигабитов выгарело, а 5 по 100 остались) с экранчиком... будет график рисовать загрузки канала - как я люблю 👍

**Comment by jekhor** [comment]
On Sat, Apr 01, 2017 at 03:15:37AM -0700, Olgerd wrote:
> могу найти лишний микротик... поставить его вместо зухеля, чтобы он и VPN в интернет поднимал и какой нибудь VPN over IPSec поднимал :)

А зачем? :)

И, кстати, есть trendnet, который Паша передал, можно посмотреть, что он
умеет

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/spynet/issues/5#issuecomment-290910995

-- 
Yauhen Kharuzhy

**Comment by abitrolly** [comment]
Не прошло и 4 года как сделали MikroTik торчащим наружу (#17). За это время в kernel добавили https://www.wireguard.com/ но пока в микротиках иего нема что https://forum.mikrotik.com/viewtopic.php?t=156436#p783542

**Comment by abitrolly** [comment]
@Olgerd96 

> есть даже RackMount (там 5 гигабитов выгарело, а 5 по 100 остались) с экранчиком... будет график рисовать загрузки канала - как я люблю +1

В Малиновом закончились порты. +4 порта весьма пригодится. )

**Comment by abitrolly** [comment]
В RouterOS 7.1 beta 2 добавили поддержку WireGuard - https://www.reddit.com/r/mikrotik/comments/idvsxn/wireguard_support_71beta2/

**Comment by abitrolly** [comment]
Пока настраиваю L2TP в malino.mhs.by по каким-то скриптам с реддита.

https://www.reddit.com/r/mikrotik/comments/ifuwyc/recommendations_for_best_vpn_setup_with_mobile/

* [x] Пул айпишников в локалку есть. На 244 адреса. 

![image](https://user-images.githubusercontent.com/8781107/91162671-0edcdf00-e6d5-11ea-914b-340ad6e9aa21.png)

* [x] Заенаблить `l2tp-server` 
```
[admin@MHS-MikroTik] /interface l2tp-server> server print 
               enabled: no
               max-mtu: 1450
               max-mru: 1450
                  mrru: disabled
        authentication: pap,chap,mschap1,mschap2
     keepalive-timeout: 30
          max-sessions: unlimited
       default-profile: default-encryption
             use-ipsec: no
          ipsec-secret: 
        caller-id-type: ip-address
  one-session-per-host: no
       allow-fast-path: no
```
